#!/bin/sh

# wget -c -O 001-railscasts-001-caching-with-instance-variables.mp4 http://media.railscasts.com/assets/episodes/videos/001-caching-with-instance-variables.mp4
# wget -c -O 002-railscasts-002-dynamic-find-by-methods.mp4 http://media.railscasts.com/assets/episodes/videos/002-dynamic-find-by-methods.mp4
# wget -c -O 003-railscasts-003-find-through-association.mp4 http://media.railscasts.com/assets/episodes/videos/003-find-through-association.mp4
# wget -c -O 004-railscasts-004-move-find-into-model.mp4 http://media.railscasts.com/assets/episodes/videos/004-move-find-into-model.mp4
# wget -c -O 005-railscasts-005-using-with-scope.mp4 http://media.railscasts.com/assets/episodes/videos/005-using-with-scope.mp4
# wget -c -O 006-railscasts-006-shortcut-blocks-with-symbol-to-proc.mp4 http://media.railscasts.com/assets/episodes/videos/006-shortcut-blocks-with-symbol-to-proc.mp4
# wget -c -O 007-railscasts-007-all-about-layouts.mp4 http://media.railscasts.com/assets/episodes/videos/007-all-about-layouts.mp4
# wget -c -O 008-railscasts-008-layouts-and-content-for.mp4 http://media.railscasts.com/assets/episodes/videos/008-layouts-and-content-for.mp4
# wget -c -O 009-railscasts-009-filtering-sensitive-logs.mp4 http://media.railscasts.com/assets/episodes/videos/009-filtering-sensitive-logs.mp4
# wget -c -O 010-railscasts-010-refactoring-user-name-part-1.mp4 http://media.railscasts.com/assets/episodes/videos/010-refactoring-user-name-part-1.mp4
# wget -c -O 011-railscasts-011-refactoring-user-name-part-2.mp4 http://media.railscasts.com/assets/episodes/videos/011-refactoring-user-name-part-2.mp4
# wget -c -O 012-railscasts-012-refactoring-user-name-part-3.mp4 http://media.railscasts.com/assets/episodes/videos/012-refactoring-user-name-part-3.mp4
# wget -c -O 013-railscasts-013-dangers-of-model-in-session.mp4 http://media.railscasts.com/assets/episodes/videos/013-dangers-of-model-in-session.mp4
# wget -c -O 014-railscasts-014-performing-calculations-on-models.mp4 http://media.railscasts.com/assets/episodes/videos/014-performing-calculations-on-models.mp4
# wget -c -O 015-railscasts-015-fun-with-find-conditions.mp4 http://media.railscasts.com/assets/episodes/videos/015-fun-with-find-conditions.mp4
# wget -c -O 016-railscasts-016-virtual-attributes.mp4 http://media.railscasts.com/assets/episodes/videos/016-virtual-attributes.mp4
# wget -c -O 017-railscasts-017-habtm-checkboxes.mp4 http://media.railscasts.com/assets/episodes/videos/017-habtm-checkboxes.mp4
# wget -c -O 018-railscasts-018-looping-through-flash.mp4 http://media.railscasts.com/assets/episodes/videos/018-looping-through-flash.mp4
# wget -c -O 019-railscasts-019-where-administration-goes.mp4 http://media.railscasts.com/assets/episodes/videos/019-where-administration-goes.mp4
# wget -c -O 020-railscasts-020-restricting-access.mp4 http://media.railscasts.com/assets/episodes/videos/020-restricting-access.mp4
# wget -c -O 021-railscasts-021-super-simple-authentication.mp4 http://media.railscasts.com/assets/episodes/videos/021-super-simple-authentication.mp4
# wget -c -O 022-railscasts-022-eager-loading.mp4 http://media.railscasts.com/assets/episodes/videos/022-eager-loading.mp4
# wget -c -O 023-railscasts-023-counter-cache-column.mp4 http://media.railscasts.com/assets/episodes/videos/023-counter-cache-column.mp4
# wget -c -O 024-railscasts-024-the-stack-trace.mp4 http://media.railscasts.com/assets/episodes/videos/024-the-stack-trace.mp4
# wget -c -O 025-railscasts-025-sql-injection.mp4 http://media.railscasts.com/assets/episodes/videos/025-sql-injection.mp4
# wget -c -O 026-railscasts-026-hackers-love-mass-assignment.mp4 http://media.railscasts.com/assets/episodes/videos/026-hackers-love-mass-assignment.mp4
# wget -c -O 027-railscasts-027-cross-site-scripting.mp4 http://media.railscasts.com/assets/episodes/videos/027-cross-site-scripting.mp4
# wget -c -O 028-railscasts-028-in-groups-of.mp4 http://media.railscasts.com/assets/episodes/videos/028-in-groups-of.mp4
# wget -c -O 029-railscasts-029-group-by-month.mp4 http://media.railscasts.com/assets/episodes/videos/029-group-by-month.mp4
# wget -c -O 030-railscasts-030-pretty-page-title.mp4 http://media.railscasts.com/assets/episodes/videos/030-pretty-page-title.mp4
# wget -c -O 031-railscasts-031-formatting-time.mp4 http://media.railscasts.com/assets/episodes/videos/031-formatting-time.mp4
# wget -c -O 032-railscasts-032-time-in-text-field.mp4 http://media.railscasts.com/assets/episodes/videos/032-time-in-text-field.mp4
# wget -c -O 033-railscasts-033-making-a-plugin.mp4 http://media.railscasts.com/assets/episodes/videos/033-making-a-plugin.mp4
# wget -c -O 034-railscasts-034-named-routes.mp4 http://media.railscasts.com/assets/episodes/videos/034-named-routes.mp4
# wget -c -O 035-railscasts-035-custom-rest-actions.mp4 http://media.railscasts.com/assets/episodes/videos/035-custom-rest-actions.mp4
# wget -c -O 036-railscasts-036-subversion-on-rails.mp4 http://media.railscasts.com/assets/episodes/videos/036-subversion-on-rails.mp4
# wget -c -O 037-railscasts-037-simple-search-form.mp4 http://media.railscasts.com/assets/episodes/videos/037-simple-search-form.mp4
# wget -c -O 038-railscasts-038-multibutton-form.mp4 http://media.railscasts.com/assets/episodes/videos/038-multibutton-form.mp4
# wget -c -O 039-railscasts-039-customize-field-error.mp4 http://media.railscasts.com/assets/episodes/videos/039-customize-field-error.mp4
# wget -c -O 040-railscasts-040-blocks-in-view.mp4 http://media.railscasts.com/assets/episodes/videos/040-blocks-in-view.mp4
# wget -c -O 041-railscasts-041-conditional-validations.mp4 http://media.railscasts.com/assets/episodes/videos/041-conditional-validations.mp4
# wget -c -O 042-railscasts-042-with-options.mp4 http://media.railscasts.com/assets/episodes/videos/042-with-options.mp4
# wget -c -O 043-railscasts-043-ajax-with-rjs.mp4 http://media.railscasts.com/assets/episodes/videos/043-ajax-with-rjs.mp4
# wget -c -O 044-railscasts-044-debugging-rjs.mp4 http://media.railscasts.com/assets/episodes/videos/044-debugging-rjs.mp4
# wget -c -O 045-railscasts-045-rjs-tips.mp4 http://media.railscasts.com/assets/episodes/videos/045-rjs-tips.mp4
# wget -c -O 046-railscasts-046-catch-all-route.mp4 http://media.railscasts.com/assets/episodes/videos/046-catch-all-route.mp4
# wget -c -O 047-railscasts-047-two-many-to-many.mp4 http://media.railscasts.com/assets/episodes/videos/047-two-many-to-many.mp4
# wget -c -O 048-railscasts-048-console-tricks.mp4 http://media.railscasts.com/assets/episodes/videos/048-console-tricks.mp4
# wget -c -O 049-railscasts-049-reading-the-api.mp4 http://media.railscasts.com/assets/episodes/videos/049-reading-the-api.mp4
# wget -c -O 050-railscasts-050-contributing-to-rails.mp4 http://media.railscasts.com/assets/episodes/videos/050-contributing-to-rails.mp4
# wget -c -O 051-railscasts-051-will-paginate.mp4 http://media.railscasts.com/assets/episodes/videos/051-will-paginate.mp4
# wget -c -O 052-railscasts-052-update-through-checkboxes.mp4 http://media.railscasts.com/assets/episodes/videos/052-update-through-checkboxes.mp4
# wget -c -O 053-railscasts-053-handling-exceptions.mp4 http://media.railscasts.com/assets/episodes/videos/053-handling-exceptions.mp4
# wget -c -O 054-railscasts-054-debugging-with-ruby-debug.mp4 http://media.railscasts.com/assets/episodes/videos/054-debugging-with-ruby-debug.mp4
# wget -c -O 055-railscasts-055-cleaning-up-the-view.mp4 http://media.railscasts.com/assets/episodes/videos/055-cleaning-up-the-view.mp4
# wget -c -O 056-railscasts-056-the-logger.mp4 http://media.railscasts.com/assets/episodes/videos/056-the-logger.mp4
# wget -c -O 057-railscasts-057-create-model-through-text-field.mp4 http://media.railscasts.com/assets/episodes/videos/057-create-model-through-text-field.mp4
# wget -c -O 058-railscasts-058-how-to-make-a-generator.mp4 http://media.railscasts.com/assets/episodes/videos/058-how-to-make-a-generator.mp4
# wget -c -O 059-railscasts-059-optimistic-locking.mp4 http://media.railscasts.com/assets/episodes/videos/059-optimistic-locking.mp4
# wget -c -O 060-railscasts-060-testing-without-fixtures.mp4 http://media.railscasts.com/assets/episodes/videos/060-testing-without-fixtures.mp4
# wget -c -O 061-railscasts-061-sending-email.mp4 http://media.railscasts.com/assets/episodes/videos/061-sending-email.mp4
# wget -c -O 062-railscasts-062-hacking-activerecord.mp4 http://media.railscasts.com/assets/episodes/videos/062-hacking-activerecord.mp4
# wget -c -O 063-railscasts-063-model-name-in-url.mp4 http://media.railscasts.com/assets/episodes/videos/063-model-name-in-url.mp4
# wget -c -O 064-railscasts-064-custom-helper-modules.mp4 http://media.railscasts.com/assets/episodes/videos/064-custom-helper-modules.mp4
# wget -c -O 065-railscasts-065-stopping-spam-with-akismet.mp4 http://media.railscasts.com/assets/episodes/videos/065-stopping-spam-with-akismet.mp4
# wget -c -O 066-railscasts-066-custom-rake-tasks.mp4 http://media.railscasts.com/assets/episodes/videos/066-custom-rake-tasks.mp4
# wget -c -O 067-railscasts-067-restful-authentication.mp4 http://media.railscasts.com/assets/episodes/videos/067-restful-authentication.mp4
# wget -c -O 068-railscasts-068-openid-authentication.mp4 http://media.railscasts.com/assets/episodes/videos/068-openid-authentication.mp4
# wget -c -O 069-railscasts-069-markaby-in-helper.mp4 http://media.railscasts.com/assets/episodes/videos/069-markaby-in-helper.mp4
# wget -c -O 070-railscasts-070-custom-routes.mp4 http://media.railscasts.com/assets/episodes/videos/070-custom-routes.mp4
# wget -c -O 071-railscasts-071-testing-controllers-with-rspec.mp4 http://media.railscasts.com/assets/episodes/videos/071-testing-controllers-with-rspec.mp4
# wget -c -O 072-railscasts-072-adding-an-environment.mp4 http://media.railscasts.com/assets/episodes/videos/072-adding-an-environment.mp4
# wget -c -O 073-railscasts-073-complex-forms-part-1.mp4 http://media.railscasts.com/assets/episodes/videos/073-complex-forms-part-1.mp4
# wget -c -O 074-railscasts-074-complex-forms-part-2.mp4 http://media.railscasts.com/assets/episodes/videos/074-complex-forms-part-2.mp4
# wget -c -O 075-railscasts-075-complex-forms-part-3.mp4 http://media.railscasts.com/assets/episodes/videos/075-complex-forms-part-3.mp4
# wget -c -O 076-railscasts-076-scope-out.mp4 http://media.railscasts.com/assets/episodes/videos/076-scope-out.mp4
# wget -c -O 077-railscasts-077-destroy-without-javascript.mp4 http://media.railscasts.com/assets/episodes/videos/077-destroy-without-javascript.mp4
# wget -c -O 078-railscasts-078-generating-pdf-documents.mp4 http://media.railscasts.com/assets/episodes/videos/078-generating-pdf-documents.mp4
# wget -c -O 079-railscasts-079-generate-named-routes.mp4 http://media.railscasts.com/assets/episodes/videos/079-generate-named-routes.mp4
# wget -c -O 080-railscasts-080-simplify-views-with-rails-2-0.mp4 http://media.railscasts.com/assets/episodes/videos/080-simplify-views-with-rails-2-0.mp4
# wget -c -O 081-railscasts-081-fixtures-in-rails-2-0.mp4 http://media.railscasts.com/assets/episodes/videos/081-fixtures-in-rails-2-0.mp4
# wget -c -O 082-railscasts-082-http-basic-authentication.mp4 http://media.railscasts.com/assets/episodes/videos/082-http-basic-authentication.mp4
# wget -c -O 083-railscasts-083-migrations-in-rails-2-0.mp4 http://media.railscasts.com/assets/episodes/videos/083-migrations-in-rails-2-0.mp4
# wget -c -O 084-railscasts-084-cookie-based-session-store.mp4 http://media.railscasts.com/assets/episodes/videos/084-cookie-based-session-store.mp4
# wget -c -O 085-railscasts-085-yaml-configuration-file.mp4 http://media.railscasts.com/assets/episodes/videos/085-yaml-configuration-file.mp4
# wget -c -O 086-railscasts-086-logging-variables.mp4 http://media.railscasts.com/assets/episodes/videos/086-logging-variables.mp4
# wget -c -O 087-railscasts-087-generating-rss-feeds.mp4 http://media.railscasts.com/assets/episodes/videos/087-generating-rss-feeds.mp4
# wget -c -O 088-railscasts-088-dynamic-select-menus.mp4 http://media.railscasts.com/assets/episodes/videos/088-dynamic-select-menus.mp4
# wget -c -O 089-railscasts-089-page-caching.mp4 http://media.railscasts.com/assets/episodes/videos/089-page-caching.mp4
# wget -c -O 090-railscasts-090-fragment-caching.mp4 http://media.railscasts.com/assets/episodes/videos/090-fragment-caching.mp4
# wget -c -O 091-railscasts-091-refactoring-long-methods.mp4 http://media.railscasts.com/assets/episodes/videos/091-refactoring-long-methods.mp4
# wget -c -O 092-railscasts-092-make-resourceful.mp4 http://media.railscasts.com/assets/episodes/videos/092-make-resourceful.mp4
# wget -c -O 093-railscasts-093-action-caching.mp4 http://media.railscasts.com/assets/episodes/videos/093-action-caching.mp4
# wget -c -O 094-railscasts-094-activeresource-basics.mp4 http://media.railscasts.com/assets/episodes/videos/094-activeresource-basics.mp4
# wget -c -O 095-railscasts-095-more-on-activeresource.mp4 http://media.railscasts.com/assets/episodes/videos/095-more-on-activeresource.mp4
# wget -c -O 096-railscasts-096-git-on-rails.mp4 http://media.railscasts.com/assets/episodes/videos/096-git-on-rails.mp4
# wget -c -O 097-railscasts-097-analyzing-the-production-log.mp4 http://media.railscasts.com/assets/episodes/videos/097-analyzing-the-production-log.mp4
# wget -c -O 098-railscasts-098-request-profiling.mp4 http://media.railscasts.com/assets/episodes/videos/098-request-profiling.mp4
# wget -c -O 099-railscasts-099-complex-partials.mp4 http://media.railscasts.com/assets/episodes/videos/099-complex-partials.mp4
# wget -c -O 100-railscasts-100-5-view-tips.mp4 http://media.railscasts.com/assets/episodes/videos/100-5-view-tips.mp4
# wget -c -O 101-railscasts-101-refactoring-out-helper-object.mp4 http://media.railscasts.com/assets/episodes/videos/101-refactoring-out-helper-object.mp4
# wget -c -O 102-railscasts-102-auto-complete-association.mp4 http://media.railscasts.com/assets/episodes/videos/102-auto-complete-association.mp4
# wget -c -O 103-railscasts-103-site-wide-announcements.mp4 http://media.railscasts.com/assets/episodes/videos/103-site-wide-announcements.mp4
# wget -c -O 104-railscasts-104-exception-notifications.mp4 http://media.railscasts.com/assets/episodes/videos/104-exception-notifications.mp4
# wget -c -O 105-railscasts-105-gitting-rails-2-1-rc1.mp4 http://media.railscasts.com/assets/episodes/videos/105-gitting-rails-2-1-rc1.mp4
# wget -c -O 106-railscasts-106-time-zones-in-rails-2-1.mp4 http://media.railscasts.com/assets/episodes/videos/106-time-zones-in-rails-2-1.mp4
# wget -c -O 107-railscasts-107-migrations-in-rails-2-1.mp4 http://media.railscasts.com/assets/episodes/videos/107-migrations-in-rails-2-1.mp4
# wget -c -O 108-railscasts-108-named-scope.mp4 http://media.railscasts.com/assets/episodes/videos/108-named-scope.mp4
# wget -c -O 109-railscasts-109-tracking-attribute-changes.mp4 http://media.railscasts.com/assets/episodes/videos/109-tracking-attribute-changes.mp4
# wget -c -O 110-railscasts-110-gem-dependencies.mp4 http://media.railscasts.com/assets/episodes/videos/110-gem-dependencies.mp4
# wget -c -O 111-railscasts-111-advanced-search-form.mp4 http://media.railscasts.com/assets/episodes/videos/111-advanced-search-form.mp4
# wget -c -O 112-railscasts-112-anonymous-scopes.mp4 http://media.railscasts.com/assets/episodes/videos/112-anonymous-scopes.mp4
# wget -c -O 113-railscasts-113-contributing-to-rails-with-git.mp4 http://media.railscasts.com/assets/episodes/videos/113-contributing-to-rails-with-git.mp4
# wget -c -O 114-railscasts-114-endless-page.mp4 http://media.railscasts.com/assets/episodes/videos/114-endless-page.mp4
# wget -c -O 115-railscasts-115-caching-in-rails-2-1.mp4 http://media.railscasts.com/assets/episodes/videos/115-caching-in-rails-2-1.mp4
# wget -c -O 116-railscasts-116-selenium.mp4 http://media.railscasts.com/assets/episodes/videos/116-selenium.mp4
# wget -c -O 117-railscasts-117-semi-static-pages.mp4 http://media.railscasts.com/assets/episodes/videos/117-semi-static-pages.mp4
# wget -c -O 118-railscasts-118-liquid.mp4 http://media.railscasts.com/assets/episodes/videos/118-liquid.mp4
# wget -c -O 119-railscasts-119-session-based-model.mp4 http://media.railscasts.com/assets/episodes/videos/119-session-based-model.mp4
# wget -c -O 120-railscasts-120-thinking-sphinx.mp4 http://media.railscasts.com/assets/episodes/videos/120-thinking-sphinx.mp4
# wget -c -O 121-railscasts-121-non-active-record-model.mp4 http://media.railscasts.com/assets/episodes/videos/121-non-active-record-model.mp4
# wget -c -O 122-railscasts-122-passenger-in-development.mp4 http://media.railscasts.com/assets/episodes/videos/122-passenger-in-development.mp4
# wget -c -O 123-railscasts-123-subdomains.mp4 http://media.railscasts.com/assets/episodes/videos/123-subdomains.mp4
# wget -c -O 124-railscasts-124-beta-invitations.mp4 http://media.railscasts.com/assets/episodes/videos/124-beta-invitations.mp4
# wget -c -O 125-railscasts-125-dynamic-layouts.mp4 http://media.railscasts.com/assets/episodes/videos/125-dynamic-layouts.mp4
# wget -c -O 126-railscasts-126-populating-a-database.mp4 http://media.railscasts.com/assets/episodes/videos/126-populating-a-database.mp4
# wget -c -O 127-railscasts-127-rake-in-background.mp4 http://media.railscasts.com/assets/episodes/videos/127-rake-in-background.mp4
# wget -c -O 128-railscasts-128-starling-and-workling.mp4 http://media.railscasts.com/assets/episodes/videos/128-starling-and-workling.mp4
# wget -c -O 129-railscasts-129-custom-daemon.mp4 http://media.railscasts.com/assets/episodes/videos/129-custom-daemon.mp4
# wget -c -O 130-railscasts-130-monitoring-with-god.mp4 http://media.railscasts.com/assets/episodes/videos/130-monitoring-with-god.mp4
# wget -c -O 131-railscasts-131-going-back.mp4 http://media.railscasts.com/assets/episodes/videos/131-going-back.mp4
# wget -c -O 132-railscasts-132-helpers-outside-views.mp4 http://media.railscasts.com/assets/episodes/videos/132-helpers-outside-views.mp4
# wget -c -O 133-railscasts-133-capistrano-tasks.mp4 http://media.railscasts.com/assets/episodes/videos/133-capistrano-tasks.mp4
# wget -c -O 134-railscasts-134-paperclip.mp4 http://media.railscasts.com/assets/episodes/videos/134-paperclip.mp4
# wget -c -O 135-railscasts-135-making-a-gem.mp4 http://media.railscasts.com/assets/episodes/videos/135-making-a-gem.mp4
# wget -c -O 136-railscasts-136-jquery.mp4 http://media.railscasts.com/assets/episodes/videos/136-jquery.mp4
# wget -c -O 137-railscasts-137-memoization.mp4 http://media.railscasts.com/assets/episodes/videos/137-memoization.mp4
# wget -c -O 138-railscasts-138-i18n.mp4 http://media.railscasts.com/assets/episodes/videos/138-i18n.mp4
# wget -c -O 139-railscasts-139-nested-resources.mp4 http://media.railscasts.com/assets/episodes/videos/139-nested-resources.mp4
# wget -c -O 140-railscasts-140-rails-2-2-extras.mp4 http://media.railscasts.com/assets/episodes/videos/140-rails-2-2-extras.mp4
# wget -c -O 141-railscasts-141-paypal-basics.mp4 http://media.railscasts.com/assets/episodes/videos/141-paypal-basics.mp4
# wget -c -O 142-railscasts-142-paypal-notifications.mp4 http://media.railscasts.com/assets/episodes/videos/142-paypal-notifications.mp4
# wget -c -O 143-railscasts-143-paypal-security.mp4 http://media.railscasts.com/assets/episodes/videos/143-paypal-security.mp4
# wget -c -O 144-railscasts-144-active-merchant-basics.mp4 http://media.railscasts.com/assets/episodes/videos/144-active-merchant-basics.mp4
# wget -c -O 145-railscasts-145-integrating-active-merchant.mp4 http://media.railscasts.com/assets/episodes/videos/145-integrating-active-merchant.mp4
# wget -c -O 146-railscasts-146-paypal-express-checkout.mp4 http://media.railscasts.com/assets/episodes/videos/146-paypal-express-checkout.mp4
# wget -c -O 147-railscasts-147-sortable-lists.mp4 http://media.railscasts.com/assets/episodes/videos/147-sortable-lists.mp4
# wget -c -O 148-railscasts-148-app-templates-in-rails-2-3.mp4 http://media.railscasts.com/assets/episodes/videos/148-app-templates-in-rails-2-3.mp4
# wget -c -O 149-railscasts-149-rails-engines.mp4 http://media.railscasts.com/assets/episodes/videos/149-rails-engines.mp4
# wget -c -O 150-railscasts-150-rails-metal.mp4 http://media.railscasts.com/assets/episodes/videos/150-rails-metal.mp4
# wget -c -O 151-railscasts-151-rack-middleware.mp4 http://media.railscasts.com/assets/episodes/videos/151-rack-middleware.mp4
# wget -c -O 152-railscasts-152-rails-2-3-extras.mp4 http://media.railscasts.com/assets/episodes/videos/152-rails-2-3-extras.mp4
# wget -c -O 153-railscasts-153-pdfs-with-prawn.mp4 http://media.railscasts.com/assets/episodes/videos/153-pdfs-with-prawn.mp4
# wget -c -O 154-railscasts-154-polymorphic-association.mp4 http://media.railscasts.com/assets/episodes/videos/154-polymorphic-association.mp4
# wget -c -O 155-railscasts-155-beginning-with-cucumber.mp4 http://media.railscasts.com/assets/episodes/videos/155-beginning-with-cucumber.mp4
# wget -c -O 156-railscasts-156-webrat.mp4 http://media.railscasts.com/assets/episodes/videos/156-webrat.mp4
# wget -c -O 157-railscasts-157-rspec-matchers-macros.mp4 http://media.railscasts.com/assets/episodes/videos/157-rspec-matchers-macros.mp4
# wget -c -O 158-railscasts-158-factories-not-fixtures.mp4 http://media.railscasts.com/assets/episodes/videos/158-factories-not-fixtures.mp4
# wget -c -O 159-railscasts-159-more-on-cucumber.mp4 http://media.railscasts.com/assets/episodes/videos/159-more-on-cucumber.mp4
# wget -c -O 160-railscasts-160-authlogic.mp4 http://media.railscasts.com/assets/episodes/videos/160-authlogic.mp4
# wget -c -O 161-railscasts-161-three-profiling-tools.mp4 http://media.railscasts.com/assets/episodes/videos/161-three-profiling-tools.mp4
# wget -c -O 162-railscasts-162-tree-based-navigation.mp4 http://media.railscasts.com/assets/episodes/videos/162-tree-based-navigation.mp4
# wget -c -O 163-railscasts-163-self-referential-association.mp4 http://media.railscasts.com/assets/episodes/videos/163-self-referential-association.mp4
# wget -c -O 164-railscasts-164-cron-in-ruby.mp4 http://media.railscasts.com/assets/episodes/videos/164-cron-in-ruby.mp4
# wget -c -O 165-railscasts-165-edit-multiple.mp4 http://media.railscasts.com/assets/episodes/videos/165-edit-multiple.mp4
# wget -c -O 166-railscasts-166-metric-fu.mp4 http://media.railscasts.com/assets/episodes/videos/166-metric-fu.mp4
# wget -c -O 167-railscasts-167-more-on-virtual-attributes.mp4 http://media.railscasts.com/assets/episodes/videos/167-more-on-virtual-attributes.mp4
# wget -c -O 168-railscasts-168-feed-parsing.mp4 http://media.railscasts.com/assets/episodes/videos/168-feed-parsing.mp4
# wget -c -O 169-railscasts-169-dynamic-page-caching.mp4 http://media.railscasts.com/assets/episodes/videos/169-dynamic-page-caching.mp4
# wget -c -O 170-railscasts-170-openid-with-authlogic.mp4 http://media.railscasts.com/assets/episodes/videos/170-openid-with-authlogic.mp4
# wget -c -O 171-railscasts-171-delayed-job.mp4 http://media.railscasts.com/assets/episodes/videos/171-delayed-job.mp4
# wget -c -O 172-railscasts-172-touch-and-cache.mp4 http://media.railscasts.com/assets/episodes/videos/172-touch-and-cache.mp4
# wget -c -O 173-railscasts-173-screen-scraping-with-scrapi.mp4 http://media.railscasts.com/assets/episodes/videos/173-screen-scraping-with-scrapi.mp4
# wget -c -O 174-railscasts-174-pagination-with-ajax.mp4 http://media.railscasts.com/assets/episodes/videos/174-pagination-with-ajax.mp4
# wget -c -O 175-railscasts-175-ajax-history-and-bookmarks.mp4 http://media.railscasts.com/assets/episodes/videos/175-ajax-history-and-bookmarks.mp4
# wget -c -O 176-railscasts-176-searchlogic.mp4 http://media.railscasts.com/assets/episodes/videos/176-searchlogic.mp4
# wget -c -O 177-railscasts-177-model-versioning.mp4 http://media.railscasts.com/assets/episodes/videos/177-model-versioning.mp4
# wget -c -O 178-railscasts-178-seven-security-tips.mp4 http://media.railscasts.com/assets/episodes/videos/178-seven-security-tips.mp4
# wget -c -O 179-railscasts-179-seed-data.mp4 http://media.railscasts.com/assets/episodes/videos/179-seed-data.mp4
# wget -c -O 180-railscasts-180-finding-unused-css.mp4 http://media.railscasts.com/assets/episodes/videos/180-finding-unused-css.mp4
# wget -c -O 181-railscasts-181-include-vs-joins.mp4 http://media.railscasts.com/assets/episodes/videos/181-include-vs-joins.mp4
# wget -c -O 182-railscasts-182-cropping-images.mp4 http://media.railscasts.com/assets/episodes/videos/182-cropping-images.mp4
# wget -c -O 183-railscasts-183-gemcutter-jeweler.mp4 http://media.railscasts.com/assets/episodes/videos/183-gemcutter-jeweler.mp4
# wget -c -O 184-railscasts-184-formtastic-part-1.mp4 http://media.railscasts.com/assets/episodes/videos/184-formtastic-part-1.mp4
# wget -c -O 185-railscasts-185-formtastic-part-2.mp4 http://media.railscasts.com/assets/episodes/videos/185-formtastic-part-2.mp4
# wget -c -O 186-railscasts-186-pickle-with-cucumber.mp4 http://media.railscasts.com/assets/episodes/videos/186-pickle-with-cucumber.mp4
# wget -c -O 187-railscasts-187-testing-exceptions.mp4 http://media.railscasts.com/assets/episodes/videos/187-testing-exceptions.mp4
# wget -c -O 188-railscasts-188-declarative-authorization.mp4 http://media.railscasts.com/assets/episodes/videos/188-declarative-authorization.mp4
# wget -c -O 189-railscasts-189-embedded-association.mp4 http://media.railscasts.com/assets/episodes/videos/189-embedded-association.mp4
# wget -c -O 190-railscasts-190-screen-scraping-with-nokogiri.mp4 http://media.railscasts.com/assets/episodes/videos/190-screen-scraping-with-nokogiri.mp4
# wget -c -O 191-railscasts-191-mechanize.mp4 http://media.railscasts.com/assets/episodes/videos/191-mechanize.mp4
# wget -c -O 192-railscasts-192-authorization-with-cancan.mp4 http://media.railscasts.com/assets/episodes/videos/192-authorization-with-cancan.mp4
# wget -c -O 193-railscasts-193-tableless-model.mp4 http://media.railscasts.com/assets/episodes/videos/193-tableless-model.mp4
# wget -c -O 194-railscasts-194-mongodb-and-mongomapper.mp4 http://media.railscasts.com/assets/episodes/videos/194-mongodb-and-mongomapper.mp4
# wget -c -O 195-railscasts-195-my-favorite-web-apps-in-2009.mp4 http://media.railscasts.com/assets/episodes/videos/195-my-favorite-web-apps-in-2009.mp4
# wget -c -O 196-railscasts-196-nested-model-form-part-1.mp4 http://media.railscasts.com/assets/episodes/videos/196-nested-model-form-part-1.mp4
# wget -c -O 197-railscasts-197-nested-model-form-part-2.mp4 http://media.railscasts.com/assets/episodes/videos/197-nested-model-form-part-2.mp4
# wget -c -O 198-railscasts-198-edit-multiple-individually.mp4 http://media.railscasts.com/assets/episodes/videos/198-edit-multiple-individually.mp4
# wget -c -O 199-railscasts-199-mobile-devices.mp4 http://media.railscasts.com/assets/episodes/videos/199-mobile-devices.mp4
# wget -c -O 200-railscasts-200-rails-3-beta-and-rvm.mp4 http://media.railscasts.com/assets/episodes/videos/200-rails-3-beta-and-rvm.mp4
# wget -c -O 201-railscasts-201-bundler.mp4 http://media.railscasts.com/assets/episodes/videos/201-bundler.mp4
# wget -c -O 202-railscasts-202-active-record-queries-in-rails-3.mp4 http://media.railscasts.com/assets/episodes/videos/202-active-record-queries-in-rails-3.mp4
# wget -c -O 203-railscasts-203-routing-in-rails-3.mp4 http://media.railscasts.com/assets/episodes/videos/203-routing-in-rails-3.mp4
# wget -c -O 204-railscasts-204-xss-protection-in-rails-3.mp4 http://media.railscasts.com/assets/episodes/videos/204-xss-protection-in-rails-3.mp4
# wget -c -O 205-railscasts-205-unobtrusive-javascript.mp4 http://media.railscasts.com/assets/episodes/videos/205-unobtrusive-javascript.mp4
# wget -c -O 206-railscasts-206-action-mailer-in-rails-3.mp4 http://media.railscasts.com/assets/episodes/videos/206-action-mailer-in-rails-3.mp4
# wget -c -O 207-railscasts-207-syntax-highlighting.mp4 http://media.railscasts.com/assets/episodes/videos/207-syntax-highlighting.mp4
# wget -c -O 208-railscasts-208-erb-blocks-in-rails-3.mp4 http://media.railscasts.com/assets/episodes/videos/208-erb-blocks-in-rails-3.mp4
# wget -c -O 209-railscasts-209-introducing-devise.mp4 http://media.railscasts.com/assets/episodes/videos/209-introducing-devise.mp4
# wget -c -O 210-railscasts-210-customizing-devise.mp4 http://media.railscasts.com/assets/episodes/videos/210-customizing-devise.mp4
# wget -c -O 211-railscasts-211-validations-in-rails-3.mp4 http://media.railscasts.com/assets/episodes/videos/211-validations-in-rails-3.mp4
# wget -c -O 212-railscasts-212-refactoring-dynamic-delegator.mp4 http://media.railscasts.com/assets/episodes/videos/212-refactoring-dynamic-delegator.mp4
# wget -c -O 213-railscasts-213-calendars.mp4 http://media.railscasts.com/assets/episodes/videos/213-calendars.mp4
# wget -c -O 214-railscasts-214-a-b-testing-with-a-bingo.mp4 http://media.railscasts.com/assets/episodes/videos/214-a-b-testing-with-a-bingo.mp4
# wget -c -O 215-railscasts-215-advanced-queries-in-rails-3.mp4 http://media.railscasts.com/assets/episodes/videos/215-advanced-queries-in-rails-3.mp4
# wget -c -O 216-railscasts-216-generators-in-rails-3.mp4 http://media.railscasts.com/assets/episodes/videos/216-generators-in-rails-3.mp4
# wget -c -O 217-railscasts-217-multistep-forms.mp4 http://media.railscasts.com/assets/episodes/videos/217-multistep-forms.mp4
# wget -c -O 218-railscasts-218-making-generators-in-rails-3.mp4 http://media.railscasts.com/assets/episodes/videos/218-making-generators-in-rails-3.mp4
# wget -c -O 219-railscasts-219-active-model.mp4 http://media.railscasts.com/assets/episodes/videos/219-active-model.mp4
# wget -c -O 220-railscasts-220-pdfkit.mp4 http://media.railscasts.com/assets/episodes/videos/220-pdfkit.mp4
# wget -c -O 221-railscasts-221-subdomains-in-rails-3.mp4 http://media.railscasts.com/assets/episodes/videos/221-subdomains-in-rails-3.mp4
# wget -c -O 222-railscasts-222-rack-in-rails-3.mp4 http://media.railscasts.com/assets/episodes/videos/222-rack-in-rails-3.mp4
# wget -c -O 223-railscasts-223-charts.mp4 http://media.railscasts.com/assets/episodes/videos/223-charts.mp4
# wget -c -O 224-railscasts-224-controllers-in-rails-3.mp4 http://media.railscasts.com/assets/episodes/videos/224-controllers-in-rails-3.mp4
# wget -c -O 225-railscasts-225-upgrading-to-rails-3-part-1.mp4 http://media.railscasts.com/assets/episodes/videos/225-upgrading-to-rails-3-part-1.mp4
# wget -c -O 226-railscasts-226-upgrading-to-rails-3-part-2.mp4 http://media.railscasts.com/assets/episodes/videos/226-upgrading-to-rails-3-part-2.mp4
# wget -c -O 227-railscasts-227-upgrading-to-rails-3-part-3.mp4 http://media.railscasts.com/assets/episodes/videos/227-upgrading-to-rails-3-part-3.mp4
# wget -c -O 228-railscasts-228-sortable-table-columns.mp4 http://media.railscasts.com/assets/episodes/videos/228-sortable-table-columns.mp4
# wget -c -O 229-railscasts-229-polling-for-changes.mp4 http://media.railscasts.com/assets/episodes/videos/229-polling-for-changes.mp4
# wget -c -O 230-railscasts-230-inherited-resources.mp4 http://media.railscasts.com/assets/episodes/videos/230-inherited-resources.mp4
# wget -c -O 231-railscasts-231-routing-walkthrough.mp4 http://media.railscasts.com/assets/episodes/videos/231-routing-walkthrough.mp4
# wget -c -O 232-railscasts-232-routing-walkthrough-part-2.mp4 http://media.railscasts.com/assets/episodes/videos/232-routing-walkthrough-part-2.mp4
# wget -c -O 233-railscasts-233-engage-with-devise.mp4 http://media.railscasts.com/assets/episodes/videos/233-engage-with-devise.mp4
# wget -c -O 234-railscasts-234-simple-form.mp4 http://media.railscasts.com/assets/episodes/videos/234-simple-form.mp4
# wget -c -O 235-railscasts-235-omniauth-part-1.mp4 http://media.railscasts.com/assets/episodes/videos/235-omniauth-part-1.mp4
# wget -c -O 236-railscasts-236-omniauth-part-2.mp4 http://media.railscasts.com/assets/episodes/videos/236-omniauth-part-2.mp4
# wget -c -O 237-railscasts-237-dynamic-attr-accessible.mp4 http://media.railscasts.com/assets/episodes/videos/237-dynamic-attr-accessible.mp4
# wget -c -O 238-railscasts-238-mongoid.mp4 http://media.railscasts.com/assets/episodes/videos/238-mongoid.mp4
# wget -c -O 239-railscasts-239-activerecord-relation-walkthrough.mp4 http://media.railscasts.com/assets/episodes/videos/239-activerecord-relation-walkthrough.mp4
# wget -c -O 240-railscasts-240-search-sort-paginate-with-ajax.mp4 http://media.railscasts.com/assets/episodes/videos/240-search-sort-paginate-with-ajax.mp4
# wget -c -O 241-railscasts-241-simple-omniauth.mp4 http://media.railscasts.com/assets/episodes/videos/241-simple-omniauth.mp4
# wget -c -O 242-railscasts-242-thor.mp4 http://media.railscasts.com/assets/episodes/videos/242-thor.mp4
# wget -c -O 243-railscasts-243-beanstalkd-and-stalker.mp4 http://media.railscasts.com/assets/episodes/videos/243-beanstalkd-and-stalker.mp4
# wget -c -O 244-railscasts-244-gravatar.mp4 http://media.railscasts.com/assets/episodes/videos/244-gravatar.mp4
# wget -c -O 245-railscasts-245-new-gem-with-bundler.mp4 http://media.railscasts.com/assets/episodes/videos/245-new-gem-with-bundler.mp4
# wget -c -O 246-railscasts-246-ajax-history-state.mp4 http://media.railscasts.com/assets/episodes/videos/246-ajax-history-state.mp4
# wget -c -O 247-railscasts-247-offline-apps-part-1.mp4 http://media.railscasts.com/assets/episodes/videos/247-offline-apps-part-1.mp4
# wget -c -O 248-railscasts-248-offline-apps-part-2.mp4 http://media.railscasts.com/assets/episodes/videos/248-offline-apps-part-2.mp4
# wget -c -O 249-railscasts-249-notifications-in-rails-3.mp4 http://media.railscasts.com/assets/episodes/videos/249-notifications-in-rails-3.mp4
# wget -c -O 250-railscasts-250-authentication-from-scratch.mp4 http://media.railscasts.com/assets/episodes/videos/250-authentication-from-scratch.mp4
# wget -c -O 251-railscasts-251-metawhere-metasearch.mp4 http://media.railscasts.com/assets/episodes/videos/251-metawhere-metasearch.mp4
# wget -c -O 252-railscasts-252-metrics-metrics-metrics.mp4 http://media.railscasts.com/assets/episodes/videos/252-metrics-metrics-metrics.mp4
# wget -c -O 253-railscasts-253-carrierwave-file-uploads.mp4 http://media.railscasts.com/assets/episodes/videos/253-carrierwave-file-uploads.mp4
# wget -c -O 254-railscasts-254-pagination-with-kaminari.mp4 http://media.railscasts.com/assets/episodes/videos/254-pagination-with-kaminari.mp4
# wget -c -O 255-railscasts-255-undo-with-paper-trail.mp4 http://media.railscasts.com/assets/episodes/videos/255-undo-with-paper-trail.mp4
# wget -c -O 256-railscasts-256-i18n-backends.mp4 http://media.railscasts.com/assets/episodes/videos/256-i18n-backends.mp4
# wget -c -O 257-railscasts-257-request-specs-and-capybara.mp4 http://media.railscasts.com/assets/episodes/videos/257-request-specs-and-capybara.mp4
# wget -c -O 258-railscasts-258-token-fields.mp4 http://media.railscasts.com/assets/episodes/videos/258-token-fields.mp4
# wget -c -O 259-railscasts-259-decent-exposure.mp4 http://media.railscasts.com/assets/episodes/videos/259-decent-exposure.mp4
# wget -c -O 260-railscasts-260-messaging-with-faye.mp4 http://media.railscasts.com/assets/episodes/videos/260-messaging-with-faye.mp4
# wget -c -O 261-railscasts-261-testing-javascript-with-jasmine.mp4 http://media.railscasts.com/assets/episodes/videos/261-testing-javascript-with-jasmine.mp4
# wget -c -O 262-railscasts-262-trees-with-ancestry.mp4 http://media.railscasts.com/assets/episodes/videos/262-trees-with-ancestry.mp4
# wget -c -O 263-railscasts-263-client-side-validations.mp4 http://media.railscasts.com/assets/episodes/videos/263-client-side-validations.mp4
# wget -c -O 264-railscasts-264-guard.mp4 http://media.railscasts.com/assets/episodes/videos/264-guard.mp4
# wget -c -O 265-railscasts-265-rails-3-1-overview.mp4 http://media.railscasts.com/assets/episodes/videos/265-rails-3-1-overview.mp4
# wget -c -O 266-railscasts-266-http-streaming.mp4 http://media.railscasts.com/assets/episodes/videos/266-http-streaming.mp4
# wget -c -O 267-railscasts-267-coffeescript-basics.mp4 http://media.railscasts.com/assets/episodes/videos/267-coffeescript-basics.mp4
# wget -c -O 268-railscasts-268-sass-basics.mp4 http://media.railscasts.com/assets/episodes/videos/268-sass-basics.mp4
# wget -c -O 269-railscasts-269-template-inheritance.mp4 http://media.railscasts.com/assets/episodes/videos/269-template-inheritance.mp4
# wget -c -O 270-railscasts-270-authentication-in-rails-3-1.mp4 http://media.railscasts.com/assets/episodes/videos/270-authentication-in-rails-3-1.mp4
# wget -c -O 271-railscasts-271-resque.mp4 http://media.railscasts.com/assets/episodes/videos/271-resque.mp4
# wget -c -O 272-railscasts-272-markdown-with-redcarpet.mp4 http://media.railscasts.com/assets/episodes/videos/272-markdown-with-redcarpet.mp4
# wget -c -O 273-railscasts-273-geocoder.mp4 http://media.railscasts.com/assets/episodes/videos/273-geocoder.mp4
# wget -c -O 274-railscasts-274-remember-me-reset-password.mp4 http://media.railscasts.com/assets/episodes/videos/274-remember-me-reset-password.mp4
# wget -c -O 275-railscasts-275-how-i-test.mp4 http://media.railscasts.com/assets/episodes/videos/275-how-i-test.mp4
# wget -c -O 276-railscasts-276-testing-time-web-requests.mp4 http://media.railscasts.com/assets/episodes/videos/276-testing-time-web-requests.mp4
# wget -c -O 277-railscasts-277-mountable-engines.mp4 http://media.railscasts.com/assets/episodes/videos/277-mountable-engines.mp4
# wget -c -O 278-railscasts-278-search-with-sunspot.mp4 http://media.railscasts.com/assets/episodes/videos/278-search-with-sunspot.mp4
# wget -c -O 279-railscasts-279-understanding-the-asset-pipeline.mp4 http://media.railscasts.com/assets/episodes/videos/279-understanding-the-asset-pipeline.mp4
# wget -c -O 280-railscasts-280-pry-with-rails.mp4 http://media.railscasts.com/assets/episodes/videos/280-pry-with-rails.mp4
# wget -c -O 281-railscasts-281-foreman.mp4 http://media.railscasts.com/assets/episodes/videos/281-foreman.mp4
# wget -c -O 282-railscasts-282-upgrading-to-rails-3-1.mp4 http://media.railscasts.com/assets/episodes/videos/282-upgrading-to-rails-3-1.mp4
# wget -c -O 283-railscasts-283-authentication-with-sorcery.mp4 http://media.railscasts.com/assets/episodes/videos/283-authentication-with-sorcery.mp4
# wget -c -O 284-railscasts-284-active-admin.mp4 http://media.railscasts.com/assets/episodes/videos/284-active-admin.mp4
# wget -c -O 285-railscasts-285-spork.mp4 http://media.railscasts.com/assets/episodes/videos/285-spork.mp4
# wget -c -O 286-railscasts-286-draper.mp4 http://media.railscasts.com/assets/episodes/videos/286-draper.mp4
# wget -c -O 287-railscasts-287-presenters-from-scratch.mp4 http://media.railscasts.com/assets/episodes/videos/287-presenters-from-scratch.mp4
# wget -c -O 288-railscasts-051-will-paginate-revised.mp4 http://media.railscasts.com/assets/episodes/videos/051-will-paginate-revised.mp4
# wget -c -O 289-railscasts-288-billing-with-stripe.mp4 http://media.railscasts.com/assets/episodes/videos/288-billing-with-stripe.mp4
# wget -c -O 290-railscasts-289-paypal-recurring-billing.mp4 http://media.railscasts.com/assets/episodes/videos/289-paypal-recurring-billing.mp4
# wget -c -O 291-railscasts-147-sortable-lists-revised.mp4 http://media.railscasts.com/assets/episodes/videos/147-sortable-lists-revised.mp4
# wget -c -O 292-railscasts-290-soap-with-savon.mp4 http://media.railscasts.com/assets/episodes/videos/290-soap-with-savon.mp4
# wget -c -O 293-railscasts-291-testing-with-vcr.mp4 http://media.railscasts.com/assets/episodes/videos/291-testing-with-vcr.mp4
# wget -c -O 294-railscasts-104-exception-notifications-revised.mp4 http://media.railscasts.com/assets/episodes/videos/104-exception-notifications-revised.mp4
# wget -c -O 295-railscasts-292-virtual-machines-with-vagrant.mp4 http://media.railscasts.com/assets/episodes/videos/292-virtual-machines-with-vagrant.mp4
# wget -c -O 296-railscasts-293-nginx-unicorn.mp4 http://media.railscasts.com/assets/episodes/videos/293-nginx-unicorn.mp4
# wget -c -O 297-railscasts-158-factories-not-fixtures-revised.mp4 http://media.railscasts.com/assets/episodes/videos/158-factories-not-fixtures-revised.mp4
# wget -c -O 298-railscasts-294-playing-with-pjax.mp4 http://media.railscasts.com/assets/episodes/videos/294-playing-with-pjax.mp4
# wget -c -O 299-railscasts-295-sharing-mustache-templates.mp4 http://media.railscasts.com/assets/episodes/videos/295-sharing-mustache-templates.mp4
# wget -c -O 300-railscasts-153-pdfs-with-prawn-revised.mp4 http://media.railscasts.com/assets/episodes/videos/153-pdfs-with-prawn-revised.mp4
# wget -c -O 301-railscasts-296-mercury-editor.mp4 http://media.railscasts.com/assets/episodes/videos/296-mercury-editor.mp4
# wget -c -O 302-railscasts-297-running-javascript-in-ruby.mp4 http://media.railscasts.com/assets/episodes/videos/297-running-javascript-in-ruby.mp4
# wget -c -O 303-railscasts-102-auto-complete-association-revised.mp4 http://media.railscasts.com/assets/episodes/videos/102-auto-complete-association-revised.mp4
# wget -c -O 304-railscasts-298-getting-started-with-spree.mp4 http://media.railscasts.com/assets/episodes/videos/298-getting-started-with-spree.mp4
# wget -c -O 305-railscasts-299-rails-initialization-walkthrough.mp4 http://media.railscasts.com/assets/episodes/videos/299-rails-initialization-walkthrough.mp4
# wget -c -O 306-railscasts-111-advanced-search-form-revised.mp4 http://media.railscasts.com/assets/episodes/videos/111-advanced-search-form-revised.mp4
# wget -c -O 307-railscasts-300-contributing-to-open-source.mp4 http://media.railscasts.com/assets/episodes/videos/300-contributing-to-open-source.mp4
# wget -c -O 308-railscasts-301-extracting-a-ruby-gem.mp4 http://media.railscasts.com/assets/episodes/videos/301-extracting-a-ruby-gem.mp4
# wget -c -O 309-railscasts-088-dynamic-select-menus-revised.mp4 http://media.railscasts.com/assets/episodes/videos/088-dynamic-select-menus-revised.mp4
# wget -c -O 310-railscasts-302-in-place-editing.mp4 http://media.railscasts.com/assets/episodes/videos/302-in-place-editing.mp4
# wget -c -O 311-railscasts-303-publishing-a-gem.mp4 http://media.railscasts.com/assets/episodes/videos/303-publishing-a-gem.mp4
# wget -c -O 312-railscasts-182-cropping-images-revised.mp4 http://media.railscasts.com/assets/episodes/videos/182-cropping-images-revised.mp4
# wget -c -O 313-railscasts-304-omniauth-identity.mp4 http://media.railscasts.com/assets/episodes/videos/304-omniauth-identity.mp4
# wget -c -O 314-railscasts-305-authentication-with-warden.mp4 http://media.railscasts.com/assets/episodes/videos/305-authentication-with-warden.mp4
# wget -c -O 315-railscasts-120-thinking-sphinx-revised.mp4 http://media.railscasts.com/assets/episodes/videos/120-thinking-sphinx-revised.mp4
# wget -c -O 316-railscasts-306-elasticsearch-part-1.mp4 http://media.railscasts.com/assets/episodes/videos/306-elasticsearch-part-1.mp4
# wget -c -O 317-railscasts-307-elasticsearch-part-2.mp4 http://media.railscasts.com/assets/episodes/videos/307-elasticsearch-part-2.mp4
# wget -c -O 318-railscasts-114-endless-page-revised.mp4 http://media.railscasts.com/assets/episodes/videos/114-endless-page-revised.mp4
# wget -c -O 319-railscasts-308-oh-my-zsh.mp4 http://media.railscasts.com/assets/episodes/videos/308-oh-my-zsh.mp4
# wget -c -O 320-railscasts-309-a-shell-scripting-story.mp4 http://media.railscasts.com/assets/episodes/videos/309-a-shell-scripting-story.mp4
# wget -c -O 321-railscasts-017-habtm-checkboxes-revised.mp4 http://media.railscasts.com/assets/episodes/videos/017-habtm-checkboxes-revised.mp4
# wget -c -O 322-railscasts-310-getting-started-with-rails.mp4 http://media.railscasts.com/assets/episodes/videos/310-getting-started-with-rails.mp4
# wget -c -O 323-railscasts-311-form-builders.mp4 http://media.railscasts.com/assets/episodes/videos/311-form-builders.mp4
# wget -c -O 324-railscasts-164-cron-in-ruby-revised.mp4 http://media.railscasts.com/assets/episodes/videos/164-cron-in-ruby-revised.mp4
# wget -c -O 325-railscasts-312-sending-html-email.mp4 http://media.railscasts.com/assets/episodes/videos/312-sending-html-email.mp4
# wget -c -O 326-railscasts-313-receiving-email-with-mailman.mp4 http://media.railscasts.com/assets/episodes/videos/313-receiving-email-with-mailman.mp4
# wget -c -O 327-railscasts-171-delayed-job-revised.mp4 http://media.railscasts.com/assets/episodes/videos/171-delayed-job-revised.mp4
# wget -c -O 328-railscasts-314-pretty-urls-with-friendlyid.mp4 http://media.railscasts.com/assets/episodes/videos/314-pretty-urls-with-friendlyid.mp4
# wget -c -O 329-railscasts-315-rollout-and-degrade.mp4 http://media.railscasts.com/assets/episodes/videos/315-rollout-and-degrade.mp4
# wget -c -O 330-railscasts-123-subdomains-revised.mp4 http://media.railscasts.com/assets/episodes/videos/123-subdomains-revised.mp4
# wget -c -O 331-railscasts-316-private-pub.mp4 http://media.railscasts.com/assets/episodes/videos/316-private-pub.mp4
# wget -c -O 332-railscasts-317-rack-app-from-scratch.mp4 http://media.railscasts.com/assets/episodes/videos/317-rack-app-from-scratch.mp4
# wget -c -O 333-railscasts-072-adding-an-environment-revised.mp4 http://media.railscasts.com/assets/episodes/videos/072-adding-an-environment-revised.mp4
# wget -c -O 334-railscasts-318-upgrading-to-rails-3-2.mp4 http://media.railscasts.com/assets/episodes/videos/318-upgrading-to-rails-3-2.mp4
# wget -c -O 335-railscasts-319-rails-middleware-walkthrough.mp4 http://media.railscasts.com/assets/episodes/videos/319-rails-middleware-walkthrough.mp4
# wget -c -O 336-railscasts-150-rails-metal-revised.mp4 http://media.railscasts.com/assets/episodes/videos/150-rails-metal-revised.mp4
# wget -c -O 337-railscasts-320-jbuilder.mp4 http://media.railscasts.com/assets/episodes/videos/320-jbuilder.mp4
# wget -c -O 338-railscasts-321-http-caching.mp4 http://media.railscasts.com/assets/episodes/videos/321-http-caching.mp4
# wget -c -O 339-railscasts-089-page-caching-revised.mp4 http://media.railscasts.com/assets/episodes/videos/089-page-caching-revised.mp4
# wget -c -O 340-railscasts-322-rabl.mp4 http://media.railscasts.com/assets/episodes/videos/322-rabl.mp4
# wget -c -O 341-railscasts-323-backbone-on-rails-part-1.mp4 http://media.railscasts.com/assets/episodes/videos/323-backbone-on-rails-part-1.mp4
# wget -c -O 342-railscasts-169-dynamic-page-caching-revised.mp4 http://media.railscasts.com/assets/episodes/videos/169-dynamic-page-caching-revised.mp4
# wget -c -O 343-railscasts-324-passing-data-to-javascript.mp4 http://media.railscasts.com/assets/episodes/videos/324-passing-data-to-javascript.mp4
# wget -c -O 344-railscasts-325-backbone-on-rails-part-2.mp4 http://media.railscasts.com/assets/episodes/videos/325-backbone-on-rails-part-2.mp4
# wget -c -O 345-railscasts-090-fragment-caching-revised.mp4 http://media.railscasts.com/assets/episodes/videos/090-fragment-caching-revised.mp4
# wget -c -O 346-railscasts-326-activeattr.mp4 http://media.railscasts.com/assets/episodes/videos/326-activeattr.mp4
# wget -c -O 347-railscasts-327-minitest-with-rails.mp4 http://media.railscasts.com/assets/episodes/videos/327-minitest-with-rails.mp4
# wget -c -O 348-railscasts-250-authentication-from-scratch-revised.mp4 http://media.railscasts.com/assets/episodes/videos/250-authentication-from-scratch-revised.mp4
# wget -c -O 349-railscasts-328-twitter-bootstrap-basics.mp4 http://media.railscasts.com/assets/episodes/videos/328-twitter-bootstrap-basics.mp4
# wget -c -O 350-railscasts-329-more-on-twitter-bootstrap.mp4 http://media.railscasts.com/assets/episodes/videos/329-more-on-twitter-bootstrap.mp4
# wget -c -O 351-railscasts-234-simple-form-revised.mp4 http://media.railscasts.com/assets/episodes/videos/234-simple-form-revised.mp4
# wget -c -O 352-railscasts-330-better-sass-with-bourbon.mp4 http://media.railscasts.com/assets/episodes/videos/330-better-sass-with-bourbon.mp4
# wget -c -O 353-railscasts-331-a-b-testing-with-split.mp4 http://media.railscasts.com/assets/episodes/videos/331-a-b-testing-with-split.mp4
# wget -c -O 354-railscasts-026-hackers-love-mass-assignment-revised.mp4 http://media.railscasts.com/assets/episodes/videos/026-hackers-love-mass-assignment-revised.mp4
# wget -c -O 355-railscasts-332-refinery-cms-basics.mp4 http://media.railscasts.com/assets/episodes/videos/332-refinery-cms-basics.mp4
# wget -c -O 356-railscasts-333-extending-refinery-cms.mp4 http://media.railscasts.com/assets/episodes/videos/333-extending-refinery-cms.mp4
# wget -c -O 357-railscasts-201-bundler-revised.mp4 http://media.railscasts.com/assets/episodes/videos/201-bundler-revised.mp4
# wget -c -O 358-railscasts-334-compass-css-sprites.mp4 http://media.railscasts.com/assets/episodes/videos/334-compass-css-sprites.mp4
# wget -c -O 359-railscasts-335-deploying-to-a-vps.mp4 http://media.railscasts.com/assets/episodes/videos/335-deploying-to-a-vps.mp4
# wget -c -O 360-railscasts-133-capistrano-tasks-revised.mp4 http://media.railscasts.com/assets/episodes/videos/133-capistrano-tasks-revised.mp4
# wget -c -O 361-railscasts-336-copycopter.mp4 http://media.railscasts.com/assets/episodes/videos/336-copycopter.mp4
# wget -c -O 362-railscasts-337-capistrano-recipes.mp4 http://media.railscasts.com/assets/episodes/videos/337-capistrano-recipes.mp4
# wget -c -O 363-railscasts-138-i18n-revised.mp4 http://media.railscasts.com/assets/episodes/videos/138-i18n-revised.mp4
# wget -c -O 364-railscasts-338-globalize3.mp4 http://media.railscasts.com/assets/episodes/videos/338-globalize3.mp4
# wget -c -O 365-railscasts-339-chef-solo-basics.mp4 http://media.railscasts.com/assets/episodes/videos/339-chef-solo-basics.mp4
# wget -c -O 366-railscasts-054-debugging-ruby-revised.mp4 http://media.railscasts.com/assets/episodes/videos/054-debugging-ruby-revised.mp4
# wget -c -O 367-railscasts-340-datatables.mp4 http://media.railscasts.com/assets/episodes/videos/340-datatables.mp4
# wget -c -O 368-railscasts-341-asset-pipeline-in-production.mp4 http://media.railscasts.com/assets/episodes/videos/341-asset-pipeline-in-production.mp4
# wget -c -O 369-railscasts-056-the-logger-revised.mp4 http://media.railscasts.com/assets/episodes/videos/056-the-logger-revised.mp4
# wget -c -O 370-railscasts-342-migrating-to-postgresql.mp4 http://media.railscasts.com/assets/episodes/videos/342-migrating-to-postgresql.mp4
# wget -c -O 371-railscasts-343-full-text-search-in-postgresql.mp4 http://media.railscasts.com/assets/episodes/videos/343-full-text-search-in-postgresql.mp4
# wget -c -O 372-railscasts-196-nested-model-form-revised.mp4 http://media.railscasts.com/assets/episodes/videos/196-nested-model-form-revised.mp4
# wget -c -O 373-railscasts-344-queue-classic.mp4 http://media.railscasts.com/assets/episodes/videos/344-queue-classic.mp4
# wget -c -O 374-railscasts-345-hstore.mp4 http://media.railscasts.com/assets/episodes/videos/345-hstore.mp4
# wget -c -O 375-railscasts-061-sending-email-revised.mp4 http://media.railscasts.com/assets/episodes/videos/061-sending-email-revised.mp4
# wget -c -O 376-railscasts-346-wizard-forms-with-wicked.mp4 http://media.railscasts.com/assets/episodes/videos/346-wizard-forms-with-wicked.mp4
# wget -c -O 377-railscasts-347-rubber-and-amazon-ec2.mp4 http://media.railscasts.com/assets/episodes/videos/347-rubber-and-amazon-ec2.mp4
# wget -c -O 378-railscasts-258-token-fields-revised.mp4 http://media.railscasts.com/assets/episodes/videos/258-token-fields-revised.mp4
# wget -c -O 379-railscasts-348-the-rails-api-gem.mp4 http://media.railscasts.com/assets/episodes/videos/348-the-rails-api-gem.mp4
# wget -c -O 380-railscasts-349-rails-modularity.mp4 http://media.railscasts.com/assets/episodes/videos/349-rails-modularity.mp4
# wget -c -O 381-railscasts-207-syntax-highlighting-revised.mp4 http://media.railscasts.com/assets/episodes/videos/207-syntax-highlighting-revised.mp4
# wget -c -O 382-railscasts-350-rest-api-versioning.mp4 http://media.railscasts.com/assets/episodes/videos/350-rest-api-versioning.mp4
# wget -c -O 383-railscasts-351-a-look-at-meteor.mp4 http://media.railscasts.com/assets/episodes/videos/351-a-look-at-meteor.mp4
# wget -c -O 384-railscasts-154-polymorphic-association-revised.mp4 http://media.railscasts.com/assets/episodes/videos/154-polymorphic-association-revised.mp4
# wget -c -O 385-railscasts-352-securing-an-api.mp4 http://media.railscasts.com/assets/episodes/videos/352-securing-an-api.mp4
# wget -c -O 386-railscasts-353-oauth-with-doorkeeper.mp4 http://media.railscasts.com/assets/episodes/videos/353-oauth-with-doorkeeper.mp4
# wget -c -O 387-railscasts-087-generating-rss-feeds-revised.mp4 http://media.railscasts.com/assets/episodes/videos/087-generating-rss-feeds-revised.mp4
# wget -c -O 388-railscasts-354-squeel.mp4 http://media.railscasts.com/assets/episodes/videos/354-squeel.mp4
# wget -c -O 389-railscasts-355-hacking-with-arel.mp4 http://media.railscasts.com/assets/episodes/videos/355-hacking-with-arel.mp4
# wget -c -O 390-railscasts-241-simple-omniauth-revised.mp4 http://media.railscasts.com/assets/episodes/videos/241-simple-omniauth-revised.mp4
# wget -c -O 391-railscasts-356-dangers-of-session-hijacking.mp4 http://media.railscasts.com/assets/episodes/videos/356-dangers-of-session-hijacking.mp4
# wget -c -O 392-railscasts-357-adding-ssl.mp4 http://media.railscasts.com/assets/episodes/videos/357-adding-ssl.mp4
# wget -c -O 393-railscasts-048-console-tricks-revised.mp4 http://media.railscasts.com/assets/episodes/videos/048-console-tricks-revised.mp4
# wget -c -O 394-railscasts-358-brakeman.mp4 http://media.railscasts.com/assets/episodes/videos/358-brakeman.mp4
# wget -c -O 395-railscasts-359-twitter-integration.mp4 http://media.railscasts.com/assets/episodes/videos/359-twitter-integration.mp4
# wget -c -O 396-railscasts-077-destroy-without-javascript-revised.mp4 http://media.railscasts.com/assets/episodes/videos/077-destroy-without-javascript-revised.mp4
# wget -c -O 397-railscasts-360-facebook-authentication.mp4 http://media.railscasts.com/assets/episodes/videos/360-facebook-authentication.mp4
# wget -c -O 398-railscasts-361-facebook-graph-api.mp4 http://media.railscasts.com/assets/episodes/videos/361-facebook-graph-api.mp4
# wget -c -O 399-railscasts-261-testing-javascript-with-jasmine-revised.mp4 http://media.railscasts.com/assets/episodes/videos/261-testing-javascript-with-jasmine-revised.mp4
# wget -c -O 400-railscasts-362-exporting-csv-and-excel.mp4 http://media.railscasts.com/assets/episodes/videos/362-exporting-csv-and-excel.mp4
# wget -c -O 401-railscasts-363-facebook-open-graph.mp4 http://media.railscasts.com/assets/episodes/videos/363-facebook-open-graph.mp4
# wget -c -O 402-railscasts-209-devise-revised.mp4 http://media.railscasts.com/assets/episodes/videos/209-devise-revised.mp4
# wget -c -O 403-railscasts-364-active-record-reputation-system.mp4 http://media.railscasts.com/assets/episodes/videos/364-active-record-reputation-system.mp4
# wget -c -O 404-railscasts-365-thread-safety.mp4 http://media.railscasts.com/assets/episodes/videos/365-thread-safety.mp4
# wget -c -O 405-railscasts-235-devise-and-omniauth-revised.mp4 http://media.railscasts.com/assets/episodes/videos/235-devise-and-omniauth-revised.mp4
# wget -c -O 406-railscasts-366-sidekiq.mp4 http://media.railscasts.com/assets/episodes/videos/366-sidekiq.mp4
# wget -c -O 407-railscasts-367-celluloid.mp4 http://media.railscasts.com/assets/episodes/videos/367-celluloid.mp4
# wget -c -O 408-railscasts-016-virtual-attributes-revised.mp4 http://media.railscasts.com/assets/episodes/videos/016-virtual-attributes-revised.mp4
# wget -c -O 409-railscasts-368-miniprofiler.mp4 http://media.railscasts.com/assets/episodes/videos/368-miniprofiler.mp4
# wget -c -O 410-railscasts-369-client-side-performance.mp4 http://media.railscasts.com/assets/episodes/videos/369-client-side-performance.mp4
# wget -c -O 411-railscasts-238-mongoid-revised.mp4 http://media.railscasts.com/assets/episodes/videos/238-mongoid-revised.mp4
# wget -c -O 412-railscasts-370-ransack.mp4 http://media.railscasts.com/assets/episodes/videos/370-ransack.mp4
# wget -c -O 413-railscasts-371-strong-parameters.mp4 http://media.railscasts.com/assets/episodes/videos/371-strong-parameters.mp4
# wget -c -O 414-railscasts-059-optimistic-locking-revised.mp4 http://media.railscasts.com/assets/episodes/videos/059-optimistic-locking-revised.mp4
# wget -c -O 415-railscasts-372-bullet.mp4 http://media.railscasts.com/assets/episodes/videos/372-bullet.mp4
# wget -c -O 416-railscasts-373-zero-downtime-deployment.mp4 http://media.railscasts.com/assets/episodes/videos/373-zero-downtime-deployment.mp4
# wget -c -O 417-railscasts-213-calendars-revised.mp4 http://media.railscasts.com/assets/episodes/videos/213-calendars-revised.mp4
# wget -c -O 418-railscasts-374-image-manipulation.mp4 http://media.railscasts.com/assets/episodes/videos/374-image-manipulation.mp4
# wget -c -O 419-railscasts-375-monit.mp4 http://media.railscasts.com/assets/episodes/videos/375-monit.mp4
# wget -c -O 420-railscasts-137-memoization-revised.mp4 http://media.railscasts.com/assets/episodes/videos/137-memoization-revised.mp4
# wget -c -O 421-railscasts-376-jruby-basics.mp4 http://media.railscasts.com/assets/episodes/videos/376-jruby-basics.mp4
# wget -c -O 422-railscasts-377-trinidad.mp4 http://media.railscasts.com/assets/episodes/videos/377-trinidad.mp4
# wget -c -O 423-railscasts-117-semi-static-pages-revised.mp4 http://media.railscasts.com/assets/episodes/videos/117-semi-static-pages-revised.mp4
# wget -c -O 424-railscasts-378-fnordmetric.mp4 http://media.railscasts.com/assets/episodes/videos/378-fnordmetric.mp4
# wget -c -O 425-railscasts-379-template-handlers.mp4 http://media.railscasts.com/assets/episodes/videos/379-template-handlers.mp4
# wget -c -O 426-railscasts-380-memcached-dalli.mp4 http://media.railscasts.com/assets/episodes/videos/380-memcached-dalli.mp4
# wget -c -O 427-railscasts-223-charts-graphs-revised.mp4 http://media.railscasts.com/assets/episodes/videos/223-charts-graphs-revised.mp4
# wget -c -O 428-railscasts-381-jquery-file-upload.mp4 http://media.railscasts.com/assets/episodes/videos/381-jquery-file-upload.mp4
# wget -c -O 429-railscasts-382-tagging.mp4 http://media.railscasts.com/assets/episodes/videos/382-tagging.mp4
# wget -c -O 430-railscasts-383-uploading-to-amazon-s3.mp4 http://media.railscasts.com/assets/episodes/videos/383-uploading-to-amazon-s3.mp4
# wget -c -O 431-railscasts-136-jquery-ajax-revised.mp4 http://media.railscasts.com/assets/episodes/videos/136-jquery-ajax-revised.mp4
# wget -c -O 432-railscasts-384-exploring-rubygems.mp4 http://media.railscasts.com/assets/episodes/videos/384-exploring-rubygems.mp4
# wget -c -O 433-railscasts-385-authorization-from-scratch-part-1.mp4 http://media.railscasts.com/assets/episodes/videos/385-authorization-from-scratch-part-1.mp4
# wget -c -O 434-railscasts-386-authorization-from-scratch-part-2.mp4 http://media.railscasts.com/assets/episodes/videos/386-authorization-from-scratch-part-2.mp4
# wget -c -O 435-railscasts-085-yaml-configuration-revised.mp4 http://media.railscasts.com/assets/episodes/videos/085-yaml-configuration-revised.mp4
# wget -c -O 436-railscasts-387-cache-digests.mp4 http://media.railscasts.com/assets/episodes/videos/387-cache-digests.mp4
# wget -c -O 437-railscasts-388-multitenancy-with-scopes.mp4 http://media.railscasts.com/assets/episodes/videos/388-multitenancy-with-scopes.mp4
# wget -c -O 438-railscasts-389-multitenancy-with-postgresql.mp4 http://media.railscasts.com/assets/episodes/videos/389-multitenancy-with-postgresql.mp4
# wget -c -O 439-railscasts-106-time-zones-revised.mp4 http://media.railscasts.com/assets/episodes/videos/106-time-zones-revised.mp4
# wget -c -O 440-railscasts-390-turbolinks.mp4 http://media.railscasts.com/assets/episodes/videos/390-turbolinks.mp4
# wget -c -O 441-railscasts-391-testing-javascript-with-phantomjs.mp4 http://media.railscasts.com/assets/episodes/videos/391-testing-javascript-with-phantomjs.mp4
# wget -c -O 442-railscasts-103-site-wide-announcements-revised.mp4 http://media.railscasts.com/assets/episodes/videos/103-site-wide-announcements-revised.mp4
# wget -c -O 443-railscasts-392-a-tour-of-state-machines.mp4 http://media.railscasts.com/assets/episodes/videos/392-a-tour-of-state-machines.mp4
# wget -c -O 444-railscasts-393-guest-user-record.mp4 http://media.railscasts.com/assets/episodes/videos/393-guest-user-record.mp4
# wget -c -O 445-railscasts-394-sti-and-polymorphic-associations.mp4 http://media.railscasts.com/assets/episodes/videos/394-sti-and-polymorphic-associations.mp4
# wget -c -O 446-railscasts-162-tree-based-navigation-revised.mp4 http://media.railscasts.com/assets/episodes/videos/162-tree-based-navigation-revised.mp4
# wget -c -O 447-railscasts-395-action-controller-walkthrough.mp4 http://media.railscasts.com/assets/episodes/videos/395-action-controller-walkthrough.mp4
# wget -c -O 448-railscasts-396-importing-csv-and-excel.mp4 http://media.railscasts.com/assets/episodes/videos/396-importing-csv-and-excel.mp4
# wget -c -O 449-railscasts-397-action-view-walkthrough.mp4 http://media.railscasts.com/assets/episodes/videos/397-action-view-walkthrough.mp4
# wget -c -O 450-railscasts-063-model-name-in-url-revised.mp4 http://media.railscasts.com/assets/episodes/videos/063-model-name-in-url-revised.mp4
# wget -c -O 451-railscasts-398-service-objects.mp4 http://media.railscasts.com/assets/episodes/videos/398-service-objects.mp4
# wget -c -O 452-railscasts-399-autocomplete-search-terms.mp4 http://media.railscasts.com/assets/episodes/videos/399-autocomplete-search-terms.mp4
# wget -c -O 453-railscasts-400-what-s-new-in-rails-4.mp4 http://media.railscasts.com/assets/episodes/videos/400-what-s-new-in-rails-4.mp4
# wget -c -O 454-railscasts-229-polling-for-changes-revised.mp4 http://media.railscasts.com/assets/episodes/videos/229-polling-for-changes-revised.mp4
# wget -c -O 455-railscasts-401-actioncontroller-live.mp4 http://media.railscasts.com/assets/episodes/videos/401-actioncontroller-live.mp4
# wget -c -O 456-railscasts-402-better-errors-railspanel.mp4 http://media.railscasts.com/assets/episodes/videos/402-better-errors-railspanel.mp4
# wget -c -O 457-railscasts-403-dynamic-forms.mp4 http://media.railscasts.com/assets/episodes/videos/403-dynamic-forms.mp4
# wget -c -O 458-railscasts-148-custom-app-generators-revised.mp4 http://media.railscasts.com/assets/episodes/videos/148-custom-app-generators-revised.mp4
# wget -c -O 459-railscasts-405-angularjs.mp4 http://media.railscasts.com/assets/episodes/videos/405-angularjs.mp4
# wget -c -O 460-railscasts-406-public-activity.mp4 http://media.railscasts.com/assets/episodes/videos/406-public-activity.mp4
# wget -c -O 461-railscasts-407-activity-feed-from-scratch.mp4 http://media.railscasts.com/assets/episodes/videos/407-activity-feed-from-scratch.mp4
# wget -c -O 462-railscasts-165-edit-multiple-revised.mp4 http://media.railscasts.com/assets/episodes/videos/165-edit-multiple-revised.mp4
# wget -c -O 463-railscasts-408-ember-part-1.mp4 http://media.railscasts.com/assets/episodes/videos/408-ember-part-1.mp4
# wget -c -O 464-railscasts-409-active-model-serializers.mp4 http://media.railscasts.com/assets/episodes/videos/409-active-model-serializers.mp4
# wget -c -O 465-railscasts-410-ember-part-2.mp4 http://media.railscasts.com/assets/episodes/videos/410-ember-part-2.mp4
# wget -c -O 466-railscasts-022-eager-loading-revised.mp4 http://media.railscasts.com/assets/episodes/videos/022-eager-loading-revised.mp4
# wget -c -O 467-railscasts-411-performance-testing.mp4 http://media.railscasts.com/assets/episodes/videos/411-performance-testing.mp4
# wget -c -O 468-railscasts-412-fast-rails-commands.mp4 http://media.railscasts.com/assets/episodes/videos/412-fast-rails-commands.mp4
# wget -c -O 469-railscasts-413-fast-tests.mp4 http://media.railscasts.com/assets/episodes/videos/413-fast-tests.mp4
# wget -c -O 470-railscasts-053-handling-exceptions-revised.mp4 http://media.railscasts.com/assets/episodes/videos/053-handling-exceptions-revised.mp4
# wget -c -O 471-railscasts-414-batch-api-requests.mp4 http://media.railscasts.com/assets/episodes/videos/414-batch-api-requests.mp4
# wget -c -O 472-railscasts-415-upgrading-to-rails-4.mp4 http://media.railscasts.com/assets/episodes/videos/415-upgrading-to-rails-4.mp4
# wget -c -O 473-railscasts-115-model-caching-revised.mp4 http://media.railscasts.com/assets/episodes/videos/115-model-caching-revised.mp4
# wget -c -O 474-railscasts-416-form-objects.mp4 http://media.railscasts.com/assets/episodes/videos/416-form-objects.mp4
# wget -c -O 475-railscasts-417-foundation.mp4 http://media.railscasts.com/assets/episodes/videos/417-foundation.mp4
